version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: felchat
      POSTGRES_USER: felchatuser
      POSTGRES_PASSWORD: felchatpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    # command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # command: ["./wait-for-it.sh", "db", "5432", "--", "python", "manage.py", "migrate && python manage.py runserver 0.0.0.0:8000"]
    command: >
      sh -c "/wait-for-it.sh db 5432 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
