version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: felchat
      POSTGRES_USER: felchatuser
      POSTGRES_PASSWORD: felchatpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U felchatuser -d felchat"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    command: > 
      sh -c "/wait-for-it.sh db 5432 -- \
             python manage.py migrate && \
             python manage.py ensure_initial_user && \
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db: 
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend/fel-chat
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/fel-chat:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api 
    stdin_open: true
    tty: true

volumes:
  postgres_data: